// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUkdJwSS9cXCnjw_4V18b86u1BdI1JqcI',
    appId: '1:681677905525:android:34a45f9a1d0bb542e0a23c',
    messagingSenderId: '681677905525',
    projectId: 'baby-sync',
    storageBucket: 'baby-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7x6m0RfLYTdBzPmD07cu-iRGvTG2LgbY',
    appId: '1:681677905525:ios:2695a045eecd1d0ae0a23c',
    messagingSenderId: '681677905525',
    projectId: 'baby-sync',
    storageBucket: 'baby-sync.appspot.com',
    iosClientId: '681677905525-efke58tccs6j5u8qigd5nq7hoomcsq2i.apps.googleusercontent.com',
    iosBundleId: 'app.baby.sync',
  );
}
